### ISSUE TITLE
Discussion... How do we want to store / pass global interfaces?

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1029]
I'm sure this is a topic of debate amongst the large go community, but I think we probably need to figure out what we want to do.

In the near term I see a couple of things we're likely to improve and change. 
1. I think we're going to create an interface to replace the bbolt thing. So instead of just passing a bbolt db.Client around, we'd pass an interface. The goal here is to facilitate moving away from bbolt, at least in testing. 
2. Today, we parse the flags into an opts struct, and we pass it around to a couple of places. But, as we do more with the control server, I think several of these flags will become mutable. And various libraries deep inside launcher will need access to them.

I see two basic patterns (perhaps there are more?). One pattern is to define the object, and then pass it along in all the method signatures that need it --  This is what we do with the bbolt db client. The other pattern is to create a pkg with some global state, and allow it to be invoked anywhere -- This is what we do with `agent.Keys`. I think we should settle on a pattern, and expand it to include flags. 

I can sorta think of a third pattern -- which about inverting control. Instead of having our subsystems spawned off in their own goroutines, I could imagine things registering `run` functions with something that can control all the timing and loops. But it feels like a big shift. So I'm mostly sticking with the two patterns above -- threading things through, or using a psuedo-global.

Some questions about how these are exposed in testing things

**Comment by James-Pickett** [comment]
I'm good with global interfaces that are initialized once and re-used all over the place, like `agent.Keys`

I started to digest how bolt.db / future.db might be accessed via a global thingy. As mentioned, how would we mock the global interface in a test? Everything could just have a opts pattern that can override the globals.

I will continue to ponder.

**Comment by James-Pickett** [comment]
been pondering this and today I think we should pass it around rather than access it globally the way we do agent keys

the main reason for this is the catch 22 that making it testable put us in, we need to be able to update it for testing, but we also don’t want it to be able to be modified from anywhere in the application

so I think we should pass it around the way we do a ctx …. in fact LauncherContext is not a bad name for it

to summarize, I think we should pass around a thing that gives us:

* read access to flags or other config values
* ability to get notified when one a flag/config value changes
  * but who gets to update the values? perhaps pass and updater channel when you add a flag / config that the instantiator can push to? ... maybe a little too clever?
* access to read / write to DB
* lifecycle management? perhaps this thing embeds a context or has a ctx field?

thats my feelings today, may be different tomorrow

**Comment by directionless** [comment]
I think I'm coming down on passing something around. Possible a huge superset, like `agent.Runtime` which contains smaller interfaces. But yet

**Comment by directionless** [comment]
I'm kinda imagining things like:

```
type LogStore interface
type KeyReader interface
type FlagReader interface
type Querier interface

type Runtime interface {
  LogStore
  KeyReader
  FlagReader
  Querier
}
```

But whats RW vs RO, and how it all fits I don't know

**Comment by directionless** [comment]
This is being implemented in the various PRs around `bbolt be gone` and `knapsack`
