### ISSUE TITLE
The `kolide_launcher_info` should expose runtime.

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1702]
I often want to see what the launcher runtime is. We should add that to the `kolide_launcher_info` table

**Comment by RebeccaMahany** [comment]
Do we want a new column `go_version` set to `runtime.Version()` for this issue? Or something else?

**Comment by directionless** [comment]
Heh, I guess `runtime` is pretty ambiguous. I was thinking about uptime -- how old is this process.

But maybe there are good values from `runtime` that we should expose too.

(and yes, I think new columns)

**Comment by RebeccaMahany** [comment]
Ah, I see we even already pull some of those runtime values in this table -- probably don't need to do anything other than the uptime here, then.

Proposed requirements for issue:

- On launcher startup, store the startup time (in the knapsack, or potentially in a new store like the `OsqueryHistoryInstanceStore` store if we think we might want to store history in the future)
- Modify the [kolide_launcher_info](https://github.com/kolide/launcher/blob/main/pkg/osquery/table/launcher_info.go) table to add a new column, `launcher_uptime`, which should be the number of seconds since the launcher startup time
- (Maybe we want a `launcher_uptime_friendly` column with an easily-readable string, too?)

**Comment by directionless** [comment]
Sounds right. But....
- Not sure we need `launcher_uptime_friendly`
- The table is already `launcher` I'd call the column `uptime` no need to repeat it

**Comment by RebeccaMahany** [comment]
Updated!
