### ISSUE TITLE
We should capture launcher metadata in flares

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1752]
eg: `/var/kolide-k2/k2device.kolide.com/metadata.json` and the various platform specific paths.

**Comment by RebeccaMahany** [comment]
`metadata.json` will always live in the configured root directory -- you can call `knapsack.RootDirectory()` to get the root directory.

`metadata.json` contains the same info that's provided in the [serverDataCheckup](https://github.com/kolide/launcher/blob/main/ee/debug/checkups/server_data.go), so I think we should add this file to that checkup rather than creating a new checkup. You can update `ExtraFileName` in that checkup to "metadata.json" and then writing the file to the `extraFH`.
