### ISSUE TITLE
package-builder fails on building Debs

### ISSUE THREAD

**Issue by znb** [kolide/launcher#264]
**OS X Version**: 10.13.3
**Builder Version**: 
`
package-builder - version 0.3.0-29-gc129e90
branch: 	master
revision: 	c129e90f5b6f5d14432073d59b51428d03eb21ea
build date: 	2018-02-23T14:55:27Z
build user: 	dongs
go version: 	go1.10
`

Running make with package builder gives me this error:

`./package-builder make --hostname=hello.example.com:443 --enroll_secret=happy123 --autoupdate -osquery_version=stable

/usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:430:in read': No such file or directory @ rb_sysopen - /pkgroot/usr/local/launcher/bin/launcher-systemd-installer (Errno::ENOENT)
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:430:in block in execute
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:434:in execute
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:68:in run
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:560:in run
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:133:in run
	from /usr/local/bundle/gems/fpm-1.8.1/bin/fpm:8:in <top (required)>
	from /usr/local/bundle/bin/fpm:22:in load
	from /usr/local/bundle/bin/fpm:22:in <main>
could not generate packages: could not generate linux packages: could not create deb package: exit status 1
`

Please let me know if you need any more information.

**Comment by directionless** [comment]
package-builder has been mostly re-written, I think this no longer applies

**Comment by antoinette0x53** [comment]
This issue is happening to me on a fresh install of launcher. 
launcher - version 0.11.2-dirty
  branch: 	master
  revision: 	2878f9e2cc3102c4fc341a110ade9a4d240f1c7d
  build date: 	2019-10-25
  build user: 	
  go version: 	go1.13.3


`$ ./build/package-builder make --hostname=test.com:443 -targets="linux-systemd-deb" -package_version="stable" -debug
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"2afaac885be1d705","trace_id":"beb696994b5030782093b47f6d0e06e4","trace_is_sampled":false,"ts":"2019-10-25T15:56:44.797538Z","url":"https://dl.kolide.co/kolide/osqueryd/linux/osqueryd-stable.tar.gz"}
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"0c3df2e747ac32f6","trace_id":"2ce62853b9a27133522f15bd7c03bbad","trace_is_sampled":false,"ts":"2019-10-25T15:56:46.683304Z","url":"https://dl.kolide.co/kolide/launcher/linux/launcher-stable.tar.gz"}
{"caller":"level.go:63","level":"debug","msg":"starting download","span_id":"ee7f374734778de6","trace_id":"4a5611638e7079656d070a55121d38af","trace_is_sampled":false,"ts":"2019-10-25T15:56:47.415932Z","url":"https://dl.kolide.co/kolide/osquery-extension/linux/osquery-extension-stable.tar.gz"}
could not generate packages: making package: packaging, target linux-systemd-deb: creating fpm package: /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:430:in `read': No such file or directory @ rb_sysopen - /pkgscripts/postinstall (Errno::ENOENT)
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:430:in `block in execute'
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:434:in `execute'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /usr/local/bundle/gems/fpm-1.8.1/lib/fpm/command.rb:560:in `run'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /usr/local/bundle/gems/fpm-1.8.1/bin/fpm:8:in `<top (required)>'
	from /usr/local/bundle/bin/fpm:22:in `load'
	from /usr/local/bundle/bin/fpm:22:in `<main>'
: exit status 1
`

**Comment by directionless** [comment]
These are  unreleated failures
