### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by heydonovan** [kolide/launcher#348]
Checked the `0.5.0` release, but it doesn't look like Windows is supported. However, signed up for kolide.com, and noticed there was a Windows download button. Are they different?

**Comment by groob** [comment]
As @ccoy says, the launcher is not fully ported to windows yet. Right now we deploy osquery with a grpc transport extension, which enables osquery to enroll using our extension instead of the native TLS plugins. 

https://github.com/facebook/osquery/blob/master/docs/wiki/deployment/extensions.md
https://github.com/kolide/launcher/tree/master/cmd/grpc.ext

Full windows support for launcher is coming and we port the other components of the project, and we'll likely have releases before the end of the year.

**Comment by ruslan-ryzhkov** [comment]
@groob I was able to successfully add a Windows host to Fleet using the Launcher but I ran into two issues when following the guide at https://github.com/kolide/launcher/blob/master/docs/launcher.md

1) When running `make deps`, I ran into the following syntax error: 
```Makefile:5: *** invalid syntax in conditional.  Stop.```

   This corresponds to the following line of code in the `Makefile`: 
   ```
   ifndef ($(GOPATH))
   ```

   In order to fix this error, I had to change this line to be the following instead:
   ```
   ifndef GOPATH
   ```

   I'm not sure if this is a bug in the `Makefile` itself, something with my version of Make or something with how Windows environment variables are treated. I'm using GNU Make 4.2.1, which I installed after I installed the MSYS2 installer for Windows at http://www.msys2.org/.

2) In the Launcher documentation, the second command to run is `make launcher`. However, this does not create the `osquery-extension.exe` file, which I needed. The correct command to run was `make` instead. Does the documentation need to be updated?

**Comment by rpr5x** [comment]
@groob I was able to successfully add a Windows host to Fleet using the Launcher but I ran into two issues when following the guide at https://github.com/kolide/launcher/blob/master/docs/launcher.md

1) When running `make deps`, I ran into the following syntax error: 
```Makefile:5: *** invalid syntax in conditional.  Stop.```

   This corresponds to the following line of code in the `Makefile`: 
   ```
   ifndef ($(GOPATH))
   ```

   In order to fix this error, I had to change this line to be the following instead:
   ```
   ifndef GOPATH
   ```

   I'm not sure if this is a bug in the `Makefile` itself, something with my version of Make or something with how Windows environment variables are treated. I'm using GNU Make 4.2.1, which I installed after I installed the MSYS2 installer for Windows at http://www.msys2.org/.

2) In the Launcher documentation, the second command to run is `make launcher`. However, this does not create the `osquery-extension.exe` file, which I needed. The correct command to run was `make` instead. Does the documentation need to be updated?

**Comment by cogmeta** [comment]
>make
go run cmd/make/make.go -targets=launcher -linkstamp
# github.com/kolide/launcher/cmd/launcher
cmd\launcher\control_windows.go:16:79: undefined: options
cmd\launcher\svc_windows.go:72:10: undefined: options
ts=2019-04-26T07:28:53.4989905Z caller=logutil.go:13 severity=info msg="Target Failed" err="exit status 2" target=launcher
exit status 1
make: *** [launcher] Error 1

**Comment by nikhilkhairnar** [comment]
Hello groob
Can you please provide the brief steps oon below to add windows host in kolide fleet

"Launcher is supported on windows. You'll have to build it from master. It has a install service startup option. There's also some soon to be finished work to allow the launcher package builder to create a configured MSI."

**Comment by jagadeesanmuthuvel** [comment]
Hi
Can on anyone help me in deploying fleet launcher in windows?
Please brief me step by step instructions.
