### ISSUE TITLE
add host to kolide drops another host WINDOWS

### ISSUE THREAD

**Issue by itripc** [kolide/launcher#499]
add host to kolide drops another host WINDOWS

Hello, I know very little of this tool but my daughters are into programming and cyber security and would like to learn this tool so, I am doing my best to help out.

This could very likely be USER error so any guidance would help.  I setup my windows host

with these references

https://github.com/kolide/fleet/blob/master/docs/infrastructure/adding-hosts-to-fleet.md

https://www.fertilesecurity.com/kolide/

Any many other Google searches.  I was able to get 1 Windows  host to  talk with Kolide for about 4 days, then I tried to repeat the process on a 2nd windows  host and  it failed to enrolle with Kolide

" tls_enroll.cpp:67] Failed enrollment request to https://192.168.30.16:8080/api/v1/osquery/enroll (Request error: certificate verify failed) retrying..."

Not only did it not enroll, now my working original host  is shown as Offline  in Kolide and I cannot seem to get it sync back up with Kolide. Any help my girls and I would sure appreciate it.

**Comment by directionless** [comment]
You have opened a launcher ticket, but I don't think this is a launcher bug.

The error you attached is `Request error: certificate verify failed`. That seems straightforward. The launcher client can't verify the server cert.

**Comment by itripc** [comment]
Apologies as its not so clear to me, I tried using the   --insecure   in
the osquery.flags   but of course I have the error. If you wouldn't mind
barney it down for me that be great.

**Comment by zwass** [comment]
Hi, this may be easier to debug if you join us on [osquery Slack](https://osquery-slack.herokuapp.com/). We can chat in the #kolide channel.

My guess would be the first Windows host stopped communicating because the Launcher process stopped running. Did you install it as a service or just start it from the command line?

Is it also possible you restarted the Fleet server with a different certificate? It's possible this would have caused the certificate verification error to start occurring on that first host in addition to the new host.

**Comment by terracatta** [comment]
Closing as this is likely just some confusion on how to create a valid cert chain.
