### ISSUE TITLE
On fresh install of windows, with launcher desktop enabled, a cmd prompt stays open

### ISSUE THREAD

**Issue by James-Pickett** [kolide/launcher#943]
On fresh install of windows with launcher desktop enabled, a cmd prompt stays open. This seems to go away after the first auto update.

At the time of writing this, launcher desktop is only enabled for Kolide employees.

**Comment by RebeccaMahany** [comment]
With `windowsgui` set, `launcher.exe version` won't print out its version anymore, which blocks updates because launcher validates new binaries by running the version subcommand and checking output.

Some options for adjusting behavior: https://forum.golangbridge.org/t/no-println-output-with-go-build-ldflags-h-windowsgui/7633/7
